### ISSUE TITLE
Fail to invoke modal in Views/Home/Index and Roles.

### ISSUE THREAD

**Issue by mcabram** [mguinness/IdentityManager#2]
Hi @mguinness, thank you for your share! I tried to implement this part with my own code. But I met a problem on invoking modal defined in ModalTagHelper. In this case, the New/Edit box cannot pop out properly as a modal element in Views/Home/Index and Roles. I guess bug may exist in _ViewsImports.cshtml.

 @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers   ( this's the default line )

@addTagHelper WesternSafari.Web.Helpers.*, WesternSafari.Web   ( "WesternSafari.Web" is the namespace of my .NET Core Web App. "Helpers" is the folder where ModalTagHelper.cs is. )

**Comment by mguinness** [comment]
Is the name of your assembly WesternSafari.Web.dll?  See [Managing Tag Helper scope](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-2.1#managing-tag-helper-scope) for more information.

**Comment by mcabram** [comment]
Woo...It works! Thank you!!! I change "@addTagHelper WesternSafari.Web.Helpers.*" to @addTagHelper WesternSafari.OrderWeb.Helpers.*(since I change the scope in MVC but forget to change name of .dll).
