### ISSUE TITLE
Homecontroller.cs\Line 31: "SQLite Error 1: 'no such table: AspNetRoles'."

### ISSUE THREAD

**Issue by bgoldstein14** [mguinness/IdentityManager#3]
I'm trying to do a first run. According to the README the tables should be able to be established by running the code. the identity.db3 file is created but nothing goes into it. Am I missing something here?

**Comment by bgoldstein14** [comment]
It looks like I got it to work...just needed to do "dotnet ef database update" in the IdentityManager directory. Did I miss an instruction somewhere for that?

**Comment by mguinness** [comment]
Glad that you were able to get it to work.  Feel free to create a PR for README.md if instructions are inadequate.
